#! /usr/bin/env bash

set -e $@

DRY_RUN="${DRY_RUN:-}"
FAST="${FAST:-}"
RECOVERY="${RECOVERY:-}"
INIT_OPTS="${INIT_OPTS:-}"
FSTAB_OPTS="${FSTAB_OPTS:-}"
TMPFS_BALANCE="${TMPFS_BALANCE:-}"
BTRFS_CONVERT_ARGS="${BTRFS_CONVERT_ARGS:-}"
PARENT="${PARENT:-}"
CLOUD_CLEAR_SEMAPHORE="${CLOUD_CLEAR_SEMAPHORE:-}"

# systemd -> /usr/lib/systemd/systemd
abs() { # name
  readlink -f "$(which "$1" || echo "$1")"
}

move() { # name [path]
  prog="$(abs "$1")"
  dest="$2"
  [ -z "$dest" ] && dest="/bin"
  cp -v "$prog" "/mnt/$dest/" 1>&2
  for f in $(ldd "$prog" | perl -ne '/(\/\S+) \(0x[a-z0-9]+\)/ and print "$1\n"'); do
    [ -f "/mnt/$f" -o ! -f "$f" ] && continue
    mkdir -p "/mnt/${f%/*}"
    cp -L "$f" "/mnt/$f"
  done
}

if [ -z "$PARENT" ]; then
  parent="$(cat "/proc/$(awk '{ print $4 }' "/proc/$$/stat")/cmdline")"
  if echo "$parent" | grep "/cloud/"; then
    echo "Cloud-init detected!"
    PARENT="cloud"
  fi
fi

if [ "$PARENT" != "cloud" ]; then
  echo "Warning: unknown parent $PARENT. This setting will have no effect!"
fi

if [ "$CLOUD_CLEAR_SEMAPHORE" == "auto" ]; then
  case "$(basename "$parent")" in
    "runcmd")
      CLOUD_CLEAR_SEMAPHORE="config_scripts_user"
      ;;

    *)
      CLOUD_CLEAR_SEMAPHORE=""
      echo "WARNING: Couldn't guess CLOUD_CLEAR_SEMAPHORE. This setting will have no effect!"
      ;;
  esac
  [ -n "$CLOUD_CLEAR_SEMAPHORE" ] \
    && echo "Guessing CLOUD_CLEAR_SEMAPHORE: $CLOUD_CLEAR_SEMAPHORE"
fi

echo "=== installing packages ==="

pkgs() {
  apt-get install -y btrfs-progs busybox-static
}
pkgs || { apt-get update; pkgs; }

if mount | grep "on\s\+/.*btrfs"; then
  echo "Root is already btrfs!"
  exit 0
fi

echo "=== building temporary root ==="

mount -t tmpfs -o size=100% ramdisk /mnt
df
mkdir /mnt/{old,proc,sys,dev,run}
mkdir -p /mnt/{bin,usr/bin}

linker="$(ldd "$(which cat)" | grep "ld-linux" | awk '{ print $1 }')"
echo "Detected dynamic linker $linker"
cp -Lr "${linker%/*}" "/mnt${linker%/*}"
# don't assume symlinks, just bind mount
mount --bind "/mnt${linker%/*}" "${linker%/*}"

echo '
  btrfs
  btrfs-convert
  e2fsck
  fuser
' | xargs -P 4 -I {} sh $@ -c "$(declare -f abs); $(declare -f move); move {}"

# needed for btrfs-convert
libgcc="$(find /usr/lib -name libgcc_s.so.1)"
move "$libgcc" "/lib"

busybox="$(abs busybox)"
cp "$busybox" /mnt/bin
/mnt/bin/busybox --install /mnt/bin

echo "=== replacing systemd ==="

name="systemd"
wrapper="/mnt/bin/$name-wrapper"
cat > "$wrapper" <<EOF
#!/bin/sh

set -e $INIT_OPTS

# yes, you do have to exec once for each channel
exec >/mnt/log
exec 2>/mnt/log

echo \$@ >/mnt/sysd_opts

cd /mnt
pivot_root . old
exec /bin/chroot . /init
EOF
chmod +x "$wrapper"
sysd="$(abs systemd)"
mv $sysd /systemd
ln -s "$wrapper" $sysd

echo "=== writing new init ==="

root="$(findmnt / --first-only --noheadings -o SOURCE)"
root_dev="$(echo "$root" | sed 's/[0-9]\+$//')"
echo "Discovered root dev: $root_dev"

cat > /mnt/init <<EOF
#!/bin/sh

set -e $INIT_OPTS

DRY_RUN="$DRY_RUN"
FAST="$FAST"
RECOVERY="$RECOVERY"
FSTAB_OPTS="$FSTAB_OPTS"
TMPFS_BALANCE="$TMPFS_BALANCE"
BTRFS_CONVERT_ARGS="$BTRFS_CONVERT_ARGS"

root="$root"
root_dev="$root_dev"
sysd="$sysd"

PATH="/bin:$PATH"

EOF

cat >> /mnt/init <<'EOF'
on_exit() {
   rc="$?"
   if [ "$rc" -eq 0 ]; then
     echo "=== init done ==="
     sync
     reboot -f
   else
     echo "=== init failed ==="
     sleep 5
     sync
     [ -n "$RECOVERY" ] && /bin/sh
   fi
}

trap on_exit EXIT

echo "=== unmounting old root ==="

mount --move /old/proc /proc
while ms="$(mount | grep "on /old[^ ]" | awk '{ sub("^/old", "", $3); print $3 }')"; do
  [ -z "$ms" ] && break
  m="$(echo "$ms" | head -1)"
  mkdir -p "$m"
  mount --move "/old/$m" "/$m"
done

fuser -SIGKILL --verbose --kill --mount /old
umount -l "$root"
# basically open($root, O_RDONLY | O_EXCL) with extra steps
timeout 10s sh $INIT_OPTS -c "
  while e2fsck -E journal_only -n '$root' 2>&1 | grep 'is in use' > /dev/null; do
    sleep 1;
  done"

if [ -z "$DRY_RUN" ]; then
  echo "=== converting to btrfs ==="
  btrfs-convert -L $BTRFS_CONVERT_ARGS "$root"
fi

echo "=== mounting btrfs root ==="

mount "$root" /old

if [ -z "$DRY_RUN" -o -n "$FAST" ]; then
  echo "=== removing ext4 snapshot ==="

  btrfs subvolume delete /old/ext2_saved

  echo "=== defragging ==="

  btrfs filesystem defrag -r /old

  echo "=== rebalancing ==="
  (
    seq 10 10 50 | xargs -I {} btrfs balance start /old "-dusage={}"

    free_mem="$(free -b | awk '/Mem:/ { print $7 - 50 * "$mb"}')"
    if [ \
      -n "$TMPFS_BALANCE" \
      -a "$(df -m / | awk '/\s\/$/ { print $4 }')" -le 1024 \
    ]; then
      echo "Not enough disk space for balancing, attempting to add a tmpfs device..."

      on_exit() {
        if [ -n "$loop" ]; then
          # if a device was added but this fails the filesystem will most likely die
          btrfs device remove "$loop" /old || true
          losetup -d "$loop" || true
          rm /balance.lo || true
        fi
      }
      trap on_exit EXIT

      fallocate -l "$free_mem" /balance.lo
      loop="$(losetup -f)"
      losetup -f /balance.lo
      btrfs device add "$loop" /old

    fi
    btrfs balance start /old --full-balance
  ) || echo "WARN: Couldn't balance root!"

  echo "=== updating fstab ==="
  label="$(btrfs filesystem label "$root")"
  sed -i /old/etc/fstab -e \
    "/\s\/\s/c\LABEL=$label\t/\tbtrfs\tdefaults,$FSTAB_OPTS 0 1"
fi

echo "=== fixing old root ==="
rm "/old/$sysd"
mv /old/systemd "/old/$sysd"

# echo "=== chrooting back ==="
# echo ""
# while ms="$(mount | awk '!/\/proc|\/old|\s\/\s/ { print $3 }')"; do
#   [ -z "$ms" ] && break
#   m="$(echo "$ms" | head -1)"
#   mount --move "/$m" "/old/$m"
# done
# mount --move /proc /old/proc

# sh -c '
#   sleep 2
#   ls /run/systemd || true
#   # soft reboot
#   kill -41 1
# ' &

# cd /old/
# pivot_root . mnt
# exec chroot . /sbin/init $(cat /mnt/sysd_opts)
EOF

chmod 0755 /mnt/init

echo "=== stopping all units ==="

preserve="ssh|cloud-init|tty|journald"

systemctl list-units --type=socket --plain --no-legend \
  | cat | awk '{ print $1 }' >> /sysd-state
systemctl list-units --type=service --state=running --plain --no-legend \
  | cat | awk '{ print $1 }' > /sysd-state
systemctl list-units --type=socket --plain --no-legend \
  | cat | grep -Ev "$preserve"| awk '{ print $1 }' | xargs -P 4 systemctl stop
systemctl list-units --type=service --state=running --plain --no-legend \
  | cat | grep -Ev "$preserve" | awk '{ print $1 }' | xargs -t -P 4 systemctl stop

echo "=== starting logger ==="

mount -t devtmpfs dev /mnt/dev
mkfifo /mnt/log
/bin/sh -c $'
  exec chroot /mnt /bin/sh -c \'
    while true; do
      while IFS= read -r line; do
        echo "<3>btrfs-convert: $line"
      done < /log
    done
  \' > /dev/kmsg
' &
disown $!
echo 'logger initialized' > /mnt/log

echo "=== switching root ==="

losetup -D || true
modprobe btrfs

# pivot_root won't work with MS_SHARED
mount --make-slave /
mount --make-slave /mnt

cd /mnt
/mnt/bin/sh -c "
  set -e $INIT_OPTS

  if [ '$PARENT' == 'cloud' -a -n '$CLOUD_CLEAR_SEMAPHORE' ]; then
    if timeout 5s sh -c 'while [ ! -f /var/lib/cloud/instance/sem/$CLOUD_CLEAR_SEMAPHORE ]; do sleep 1; done'; then
      rm '/var/lib/cloud/instance/sem/$CLOUD_CLEAR_SEMAPHORE'
    else
      echo 'WARNING: couldnt clear /var/lib/cloud/instance/sem/$CLOUD_CLEAR_SEMAPHORE since it wasnt created. Ignoring!'
    fi
  fi;

  exec systemctl daemon-reexec
" 2>/mnt/log 1>/mnt/log &
disown $!

[ -n "$CLOUD_CLEAR_SEMAPHORE" ] && exit 1
