#! /usr/bin/env bash

set -e $@

RECOVERY="${RECOVERY:-}"
REBOOT="${REBOOT:-}"
INIT_OPTS="${INIT_OPTS:-}"

# systemd -> /usr/lib/systemd/systemd
abs() { # name
  readlink -f "$(which "$1" || echo 1>&2 "$1 not available in PATH!")"
}

move_prog() { # name
  prog="$(abs "$1")"
  cp -v "$prog" "/mnt/bin/" 1>&2
  for f in $(ldd "$prog" | perl -ne '/(\/\S+) \(0x[a-z0-9]+\)/ and print "$1\n"'); do
    [ -n "$2" ] && echo "/mnt/${f%/*}"
    [ -f "/mnt/$f" -o ! -f "$f" ] && continue
    mkdir -p "/mnt/${f%/*}"
    cp -L "$f" "/mnt/$f"
  done
}

wrap() {
  libs="$(move_prog "$1" 1 | sort -u | tr '\n' ':')"
  name="$(basename "$1")"
  tgt="/mnt/bin/$name-wrapper"
  cat > "$tgt" <<EOF
#!/bin/sh
LD_LIBRARY_PATH="$libs" exec "/mnt/bin/$name" \$@
EOF
  chmod +x "$tgt"
  [ -n "$2" ] && echo "$tgt"
}

echo "=== installing packages ==="

pkgs() {
  apt-get install -y btrfs-progs busybox-static
}
pkgs || { apt-get update; pkgs; }

echo "=== building temporary root ==="

mount -t tmpfs ramdisk /mnt
mkdir /mnt/{old,proc,sys,dev,run}
mkdir -p /mnt/{bin,sbin,usr/bin,usr/sbin}

linker="$(ldd "$(which cat)" | grep "ld-linux" | awk '{ print $1 }')"
echo "Detected dynamic linker $linker"
cp -Lr "${linker%/*}" "/mnt${linker%/*}"
# don't assume symlinks, just bind mount
mount --bind "/mnt${linker%/*}" "${linker%/*}"

busybox="$(abs busybox)"
cp "$busybox" /mnt/bin
/mnt/bin/busybox --install /mnt/bin

move_prog btrfs
move_prog btrfs-convert
move_prog e2fsck
move_prog strace
move_prog lsof
move_prog fuser

root="$(findmnt / --first-only --noheadings -o SOURCE)"
root_dev="$(echo "$root" | sed 's/[0-9]\+$//')"
echo "Discovered root dev: $root_dev"

cat > /mnt/init <<EOF
#!/bin/sh

set -e $INIT_OPTS

root="$root"
root_dev="$root_dev"
RECOVERY="$RECOVERY"
REBOOT="$REBOOT"

EOF

cat >> /mnt/init <<'EOF'

on_exit() {
   rc="$?"
   if [ "$rc" -eq 0 ]; then
     echo "=== init done: rebooting in 5s ==="
     for i in $(seq 1 5); do
        sleep 1
        echo -n '.'
     done
     sync
     [ -n "$REBOOT" ] && reboot -f
   else
     echo "=== init failed: opening shell ==="
     sync
     [ -n "$RECOVERY" ] && /bin/sh
   fi
}

trap on_exit EXIT

echo "=== unmounting old root ==="
mount --move /old/proc /proc
mount --move /old/sys /sys
mount --move /old/dev /dev
mount --move /old/run /run
fuser -SIGKILL --verbose --kill --mount /old
umount -l "$root"
# basically open($root, O_RDONLY | O_EXCL) with extra steps
timeout 10s sh -c "while e2fsck -E journal_only -n '$root' 2>&1 | grep 'is in use' > /dev/null; do sleep 1; done"

echo "=== converting to btrfs ==="
/sbin/btrfs-convert -L "$root"

echo "=== mounting btrfs root ==="
mount "$root" /old

echo "=== removing ext4 snapshot ==="
btrfs subvolume delete /old/ext2_saved

echo "=== defragging ==="
btrfs filesystem defrag -r /old

echo "=== rebalancing ==="
btrfs balance start /old

echo "=== updating fstab ==="
sed -i -e 's/\(LABEL=DOROOT.*\)ext4/\1btrfs/' /old/etc/fstab
sed -i -e 's/errors=remount-ro/defaults/' /old/etc/fstab

echo "=== reinstalling grub ==="
mount -t proc proc /old/proc
mount -t sysfs sys /old/sys
mount -o bind /dev /old/dev
chroot /old grub-mkconfig -o /boot/grub/grub.cfg
chroot /old grub-install "$root_dev"

echo "=== rebuilding initramfs ==="
for pkg in $(chroot /old /usr/bin/dpkg -l 'linux-image-*-*' | grep ^ii | awk '{print $2}'); do
    chroot /old /usr/sbin/dpkg-reconfigure $pkg
done

echo "=== unmounting root ==="
umount /old/dev
umount /old/sys
umount /old/proc
umount /old
sync

EOF

chmod 0755 /mnt/init

echo "=== evicting systemd ==="

path="$(find /proc/1/fd -type l | xargs -n1 readlink | grep "systemd-executor" || true)"
if [ -z "$path" ]; then
  echo "Couldn't find systemd-executor!"
  exit 1
fi
wrapper="$(wrap "$path" 1)"
mv "$(readlink -f "$path")" /systemd-executor
rm -f "$path"
ln -s "$wrapper" "$path"

wrapper="$(wrap systemd 1)"
sysd="$(abs systemd)"
mv $sysd /systemd
ln -s "$wrapper" $sysd

systemctl daemon-reexec

if find /proc/1/maps -type l \
    | xargs -n1 readlink \
    | xargs -n1 findmnt --nohead -o TARGET -T \
    | grep "^/$"; then
  echo "Couldn't evict systemd! Some files are still mapped from the root."
  echo "Contents of /proc/1/maps:"
  cat /proc/1/maps
  exit 1
fi

if find /proc/1/fd -type l \
    | xargs -n1 readlink \
    | xargs -n1 findmnt --nohead -o TARGET -T \
    | grep "^/$"; then
  echo "Couldn't evict systemd! Some files is still open on the root."
  echo "Contents of /proc/1/fd:"
  ls -l /proc/1/fd
  exit 1
fi

echo "=== stopping all units ==="

preserve="cloud-init|tty|journald"

systemctl list-units --type=socket --plain --no-legend \
  | cat | awk '{ print $1 }' >> /sysd-state
systemctl list-units --type=service --state=running --plain --no-legend \
  | cat | awk '{ print $1 }' > /sysd-state
systemctl list-units --type=socket --plain --no-legend \
  | cat | grep -Ev "$preserve"| awk '{ print $1 }' | xargs systemctl stop
systemctl list-units --type=service --state=running --plain --no-legend \
  | cat | grep -Ev "$preserve" | awk '{ print $1 }' | xargs -t systemctl stop

echo "=== switching root ==="

losetup -D || true
modprobe btrfs

# pivot_root won't work with MS_SHARED
mount --make-private /
mount --make-private /mnt

cd /mnt
pivot_root . old
exec chroot . /init
